import {
  AirplaneEnginesFill,
  Android2,
  Apple,
  Backpack,
  BadgeSd,
  BalloonHeart,
  BandaidFill,
  BellFill,
  BorderTop,
  BoxSeamFill,
  BrightnessAltHigh,
  BrowserSafari,
  BuildingFillCheck,
  CheckAll,
  Eyedropper,
  Eyeglasses,
  Keyboard,
  KeyboardFill,
  TrashFill,
} from "react-bootstrap-icons";

export const primoPrizesArray = [
  { id: 1, icon: <Keyboard size={75} /> },
  { id: 2, icon: <KeyboardFill size={75} /> },
  { id: 3, icon: <Eyedropper size={75} /> },
  { id: 4, icon: <Eyeglasses size={75} /> },
  { id: 5, icon: <AirplaneEnginesFill size={75} /> },
  { id: 7, icon: <Apple size={75} /> },
  { id: 8, icon: <TrashFill size={75} /> },
  { id: 9, icon: <Android2 size={75} /> },
  { id: 10, icon: <CheckAll size={75} /> },
  { id: 11, icon: <Backpack size={75} /> },
  { id: 12, icon: <BadgeSd size={75} /> },
  { id: 13, icon: <BalloonHeart size={75} /> },
  { id: 14, icon: <BandaidFill size={75} /> },
  { id: 15, icon: <BellFill size={75} /> },
  { id: 16, icon: <BorderTop size={75} /> },
  { id: 17, icon: <BoxSeamFill size={75} /> },
  { id: 18, icon: <BrightnessAltHigh size={75} /> },
  { id: 19, icon: <BrowserSafari size={75} /> },
  { id: 20, icon: <BuildingFillCheck size={75} /> },
];
